In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/performance.csv", encoding='cp949')  
df.head()

   GENDER TEAM           EDUCATION   TRAINING  ACHIEVEMENT  ABILITY  ATTITUDE
0  female    B   bachelor's degree       none           72       72        74
1  female    C        some college  completed           69       90        88
2  female    B     master's degree       none           90       95        93
3    male    A  associate's degree       none           47       57        44
4    male    C        some college       none           76       78        75

In [3]:
df['TOTAL_SCORE'] = df['ACHIEVEMENT'] + df['ABILITY'] + df['ATTITUDE']

In [4]:
df.head()

,GENDER,TEAM,EDUCATION,TRAINING,ACHIEVEMENT,ABILITY,ATTITUDE,TOTAL_SCORE
0,female,B,bachelor's degree,none,72,72,74,218
1,female,C,some college,completed,69,90,88,247
2,female,B,master's degree,none,90,95,93,278
3,male,A,associate's degree,none,47,57,44,148
4,male,C,some college,none,76,78,75,229

In [5]:
df = df.drop(['TOTAL_SCORE'], axis='columns')
df.head()

   GENDER TEAM           EDUCATION   TRAINING  ACHIEVEMENT  ABILITY  ATTITUDE
0  female    B   bachelor's degree       none           72       72        74
1  female    C        some college  completed           69       90        88
2  female    B     master's degree       none           90       95        93
3    male    A  associate's degree       none           47       57        44
4    male    C        some college       none           76       78        75

In [6]:
res = 0
for i in range(7, 10):
    res += i

print(res)

24

In [7]:
res = 0
for i in range(1, 11):
    res += 3

print(res)

30

In [10]:
res = 0
for i in range(1,6):
    res = res + (i**2)
    print(f"{i}번째, 값 {res}")
print(res)

1번째, 값 1
2번째, 값 5
3번째, 값 14
4번째, 값 30
5번째, 값 55
55

In [11]:
res = 1
for i in range(1, 11):  # 1부터 10까지 
    res = res * i
    print(f"{i}, 값: {res}")

print(res)

1, 값: 1
2, 값: 2
3, 값: 6
4, 값: 24
5, 값: 120
6, 값: 720
7, 값: 5040
8, 값: 40320
9, 값: 362880
10, 값: 3628800
3628800

In [12]:
def facto(n):
    res = 1
    for i in range(1, n + 1): # 1부터 n까지 
        res *= i
    return res

In [13]:
facto(5)

120

In [16]:
def combination(n, x):
    res = facto(n)/(facto(x)*facto(n-x))
    return res

In [17]:
combination(4,2)

6.0

In [18]:
n = 1000000
e = (1+(1/n))**n
e

2.7182804690957534