#### 데이터 불러오기

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df1 = pd.read_csv('./data/sales1.csv', encoding='cp949')
df2 = pd.read_csv('./data/sales2.csv', encoding='cp949')
df3 = pd.read_csv('./data/sales3.csv', encoding='cp949')

In [3]:
df1.head()

       ORDERID PURCHASE_PAGE      CITY CUSTOMER_TYPE  GENDER
0  750-67-8428             A     Seoul        Member  Female
1  226-31-3081             C  Gyeonggi        Normal  Female
2  631-41-3108             A     Seoul        Normal    Male
3  123-19-1176             A     Seoul        Member    Male
4  373-73-7910             A     Seoul        Normal    Male

In [9]:
df2.head()

,ORDERID,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE
0,750-67-8428,Health and beauty,74.69,7,26.1415,548.9715
1,226-31-3081,Electronic accessories,15.28,5,3.8200,80.2200
2,631-41-3108,Home and lifestyle,46.33,7,16.2155,340.5255
3,123-19-1176,Health and beauty,58.22,8,23.2880,489.0480
4,373-73-7910,Sports and travel,86.31,7,30.2085,634.3785

In [10]:
df3.head()

,ORDERID,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
0,750-67-8428,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1
1,226-31-3081,3/8/2019,10:29,Naverpay,76.40,4.761905,3.8200,9.6
2,631-41-3108,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4
4,373-73-7910,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,NaN

-  유니크 값 확인

In [4]:
df1['PURCHASE_PAGE'].unique()

array(['A', 'C', 'B'], dtype=object)

In [5]:
df1['CITY'].unique()

array(['Seoul', 'Gyeonggi', 'Incheon'], dtype=object)

In [6]:
df1['CUSTOMER_TYPE'].unique()

array(['Member', 'Normal'], dtype=object)

In [7]:
df1['GENDER'].unique()

array(['Female', 'Male'], dtype=object)

In [8]:
df3['RATING'].unique()

array([ 9.1,  9.6,  7.4,  8.4,  nan,  4.1,  5.8,  8. ,  7.2,  5.9,  4.5,
        6.8,  7.1,  8.2,  5.7,  4.6,  6.9,  8.6,  4.4,  4.8,  5.1,  9.9,
        6. ,  8.5,  6.7,  7.7,  7.5,  7. ,  4.7,  7.6,  7.9,  6.3,  5.6,
        9.5,  8.1,  6.5,  6.1,  6.6,  5.4,  9.3, 10. ,  6.4,  4.3,  4. ,
        8.7,  9.4,  5.5,  8.3,  7.3,  4.9,  4.2,  9.2,  7.8,  5.3,  5.2,
        9. ,  8.8,  6.2,  9.8,  9.7,  5. ,  8.9])

In [11]:
df1.nunique()

ORDERID          1000
PURCHASE_PAGE       3
CITY                3
CUSTOMER_TYPE       2
GENDER              2
dtype: int64

In [12]:
df1['GENDER'].nunique()

2

In [14]:
df1['GENDER'].value_counts()

GENDER
Female    501
Male      499
Name: count, dtype: int64

#### 결측치 처리

In [15]:
df3.isnull().sum()

ORDERID                    0
DATE                       0
PURCHASE_TIME              0
PAYMENT                    0
COGS                       0
GROSS_MARGIN_PERCENTAGE    0
GROSS_INCOME               0
RATING                     4
dtype: int64

In [16]:
df3[df3['RATING'].isnull() == True]

,ORDERID,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
4,373-73-7910,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,NaN
228,466-61-5506,2/26/2019,10:52,Naverpay,544.20,4.761905,27.2100,NaN
517,521-18-7827,1/22/2019,20:46,Credit card,196.95,4.761905,9.8475,NaN
701,176-64-7711,3/27/2019,19:11,Credit card,96.96,4.761905,4.8480,NaN

In [17]:
min(df3['RATING'])

4.0

In [18]:
max(df3['RATING'])

10.0

In [19]:
df3 = df3.fillna(0)
df3.head()

,ORDERID,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
0,750-67-8428,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1
1,226-31-3081,3/8/2019,10:29,Naverpay,76.40,4.761905,3.8200,9.6
2,631-41-3108,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4
4,373-73-7910,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0

In [20]:
df3.isnull().sum()

ORDERID                    0
DATE                       0
PURCHASE_TIME              0
PAYMENT                    0
COGS                       0
GROSS_MARGIN_PERCENTAGE    0
GROSS_INCOME               0
RATING                     0
dtype: int64

In [21]:
df3[df3['RATING'].isnull() == True]

Empty DataFrame
Columns: [ORDERID, DATE, PURCHASE_TIME, PAYMENT, COGS, GROSS_MARGIN_PERCENTAGE, GROSS_INCOME, RATING]
Index: []

In [22]:
df3['PAYMENT'].unique()

array(['Samsungpay', 'Naverpay', 'Credit card', 'Samsungpay '],
      dtype=object)

In [23]:
df3['PAYMENT'] = df3['PAYMENT'].str.strip()

In [25]:
df3['PAYMENT'].unique()

array(['Samsungpay', 'Naverpay', 'Credit card'], dtype=object)

#### 데이터 결합

In [26]:
df12_inner = pd.merge(df1, df2, on='ORDERID', how='inner')
df12_inner

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785
...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Gyeonggi,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675
996,303-96-2227,B,Incheon,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900
997,727-02-1313,A,Seoul,Member,Male,Food and beverages,31.84,1,1.5920,33.4320
998,347-56-2442,A,Seoul,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110
999,849-09-3807,A,Seoul,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990

In [27]:
df12_left = pd.merge(df1, df2, on='ORDERID', how='left')
df12_left

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785
...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Gyeonggi,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675
996,303-96-2227,B,Incheon,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900
997,727-02-1313,A,Seoul,Member,Male,Food and beverages,31.84,1,1.5920,33.4320
998,347-56-2442,A,Seoul,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110
999,849-09-3807,A,Seoul,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990

In [28]:
df = pd.merge(df12_left, df3, on = 'ORDERID', how='left')

In [29]:
df.to_csv('./data/sales.csv', index=False)

#### concat

In [32]:
df001 = pd.DataFrame([['철원', 3],
                      ['혁진', 7]],
                      columns=['name', 'number'])

In [33]:
df002 = pd.DataFrame([['예인', 9],
                      ['솔이', 8]],
                      columns=['name', 'number'])

In [34]:
df003 = pd.concat([df001, df002])
df003

  name  number
0   철원       3
1   혁진       7
0   예인       9
1   솔이       8

In [35]:
df004 = df003.reset_index()
df004

   index name  number
0      0   철원       3
1      1   혁진       7
2      0   예인       9
3      1   솔이       8

In [36]:
df005 = pd.concat([df001, df002], ignore_index=True)
df005

  name  number
0   철원       3
1   혁진       7
2   예인       9
3   솔이       8

In [40]:
df001 = pd.DataFrame([['철원', 3],
                      ['혁진', 7]],
                      columns=['name', 'number'])
df001

  name  number
0   철원       3
1   혁진       7

In [38]:
df006 = pd.DataFrame([['피아노', '강사'],
                      ['노래', '매니저']],
                      columns=['hobby', 'job'])
df006

  hobby  job
0   피아노   강사
1    노래  매니저

In [39]:
df007 = pd.concat([df001, df006], axis=1) 
df007

  name  number hobby  job
0   철원       3   피아노   강사
1   혁진       7    노래  매니저

#### 데이터 조작

In [42]:
df = pd.read_csv('./data/sales.csv', encoding='cp949')
df.head()

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Naverpay,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0

In [43]:
df008 = df[['UNIT_PRICE', 'QUANTITY']]
df008

     UNIT_PRICE  QUANTITY
0         74.69         7
1         15.28         5
2         46.33         7
3         58.22         8
4         86.31         7
..          ...       ...
995       40.35         1
996       97.38        10
997       31.84         1
998       65.82         1
999       88.34         7

[1000 rows x 2 columns]

In [44]:
unit = df[df['UNIT_PRICE'] >= 50]
unit.head()

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0
5,699-14-3026,C,Gyeonggi,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Samsungpay,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Seoul,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Samsungpay,413.04,4.761905,20.6520,5.8

In [45]:
unit_ratio1 = len(unit)/len(df)
print(unit_ratio1)

0.561

In [46]:
unit_ratio2 = unit.shape[0]/df.shape[0]
print(unit_ratio2)

0.561

In [47]:
unit.shape[0]

561

In [48]:
seoul = df[df['CITY'] == 'Seoul']
seoul

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0
6,355-53-5943,A,Seoul,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Samsungpay,413.04,4.761905,20.6520,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,886-18-2897,A,Seoul,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,19:06,Credit card,282.80,4.761905,14.1400,4.5
992,745-74-0715,A,Seoul,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,20:46,Samsungpay,116.06,4.761905,5.8030,8.8
997,727-02-1313,A,Seoul,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Naverpay,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Seoul,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Naverpay,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Seoul,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Naverpay,618.38,4.761905,30.9190,6.6

In [49]:
seoul_ratio1 = len(seoul)/len(df)
print(seoul_ratio1)

0.34

In [50]:
seoul_ratio2 = seoul.shape[0]/df.shape[0]
print(seoul_ratio2)

0.34

In [51]:
unit_seoul = df[(df['UNIT_PRICE'] > 50) & (df['CITY'] == 'Seoul')]
unit_seoul.head()

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0
6,355-53-5943,A,Seoul,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Samsungpay,413.04,4.761905,20.6520,5.8
14,829-34-3910,A,Seoul,Normal,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,19:21,Naverpay,713.80,4.761905,35.6900,5.7

In [52]:
df.iloc[2,6]

np.float64(46.33)

In [53]:
df.iloc[4:8, 1:5]

  PURCHASE_PAGE      CITY CUSTOMER_TYPE  GENDER
4             A     Seoul        Normal    Male
5             C  Gyeonggi        Normal    Male
6             A     Seoul        Member  Female
7             C  Gyeonggi        Normal  Female

####  새로운 열 추가하기

In [54]:
df['PRICE_N_MILEAGE'] = df['TOTAL_PRICE'] + df['MILEAGE']
df.head()

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING,PRICE_N_MILEAGE
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1,575.113
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Naverpay,76.40,4.761905,3.8200,9.6,84.040
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,356.741
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4,512.336
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0,664.587

In [55]:
df.drop('PRICE_N_MILEAGE', axis=1, inplace=True)

In [56]:
df.head(5)

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Naverpay,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0

In [57]:
df['GRADE'] = ''

In [58]:
df.head(5)

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING,GRADE
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1,
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Naverpay,76.40,4.761905,3.8200,9.6,
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4,
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0,

In [60]:
# loc 안쓰고 iloc쓰면 에러남
n = len(df)

for i in range(n):
    total_price = df['TOTAL_PRICE'][i]

    if total_price < 200:
        df.loc[i, 'GRADE'] = 'NORMAL'
    elif 200 <= total_price < 500:
        df.loc[i, 'GRADE'] = 'VIP'
    else:
        df.loc[i, 'GRADE'] = 'VVIP'

In [61]:
df

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING,GRADE
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Samsungpay,522.83,4.761905,26.1415,9.1,VVIP
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Naverpay,76.40,4.761905,3.8200,9.6,NORMAL
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,VIP
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Samsungpay,465.76,4.761905,23.2880,8.4,VIP
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Samsungpay,604.17,4.761905,30.2085,0.0,VVIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Gyeonggi,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Samsungpay,40.35,4.761905,2.0175,6.2,NORMAL
996,303-96-2227,B,Incheon,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Samsungpay,973.80,4.761905,48.6900,4.4,VVIP
997,727-02-1313,A,Seoul,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Naverpay,31.84,4.761905,1.5920,7.7,NORMAL
998,347-56-2442,A,Seoul,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Naverpay,65.82,4.761905,3.2910,4.1,NORMAL
999,849-09-3807,A,Seoul,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Naverpay,618.38,4.761905,30.9190,6.6,VVIP

#### 날짜 다루기

In [62]:
# 연,월,일은 짝대기(-)가 정석임

In [64]:
import datetime
now = datetime.datetime.now()
print(now)

2025-10-17 09:38:11.384160

In [66]:
dt = now - datetime.timedelta(minutes = 20)
print(dt)

2025-10-17 09:18:11.384160

In [69]:
df['DATE'] = pd.to_datetime(df['DATE'], format = '%m/%d/%Y')

In [70]:
df.head(5)

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING,GRADE
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08,Samsungpay,522.83,4.761905,26.1415,9.1,VVIP
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29,Naverpay,76.40,4.761905,3.8200,9.6,NORMAL
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23,Credit card,324.31,4.761905,16.2155,7.4,VIP
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33,Samsungpay,465.76,4.761905,23.2880,8.4,VIP
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37,Samsungpay,604.17,4.761905,30.2085,0.0,VVIP

In [72]:
from datetime import datetime

In [74]:
xmas = datetime.strptime('2025-12-25', '%Y-%m-%d').date()
print(xmas)

2025-12-25

In [79]:
(xmas - df['DATE'].dt.date).astype(str).str[:5]

0      2546
1      2484
2      2489
3      2524
4      2512
       ...
995    2522
996    2490
997    2511
998    2498
999    2502
Name: DATE, Length: 1000, dtype: object

In [80]:
df['TO_XMAS'] = (xmas - df['DATE'].dt.date).astype(str).str[:5].astype(int)
df

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING,GRADE,TO_XMAS
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08,Samsungpay,522.83,4.761905,26.1415,9.1,VVIP,2546
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29,Naverpay,76.40,4.761905,3.8200,9.6,NORMAL,2484
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23,Credit card,324.31,4.761905,16.2155,7.4,VIP,2489
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33,Samsungpay,465.76,4.761905,23.2880,8.4,VIP,2524
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37,Samsungpay,604.17,4.761905,30.2085,0.0,VVIP,2512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Gyeonggi,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,13:46,Samsungpay,40.35,4.761905,2.0175,6.2,NORMAL,2522
996,303-96-2227,B,Incheon,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,17:16,Samsungpay,973.80,4.761905,48.6900,4.4,VVIP,2490
997,727-02-1313,A,Seoul,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,13:22,Naverpay,31.84,4.761905,1.5920,7.7,NORMAL,2511
998,347-56-2442,A,Seoul,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,15:33,Naverpay,65.82,4.761905,3.2910,4.1,NORMAL,2498
999,849-09-3807,A,Seoul,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,13:28,Naverpay,618.38,4.761905,30.9190,6.6,VVIP,2502

In [81]:
df010 = df.sort_values('PURCHASE_TIME', ascending=True)

In [82]:
df010.head(10)

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING,GRADE,TO_XMAS
913,522-57-8364,A,Seoul,Member,Male,Fashion accessories,51.34,8,20.5360,431.2560,2019-01-31,10:00,Samsungpay,410.72,4.761905,20.5360,7.6,VIP,2520
180,130-98-8941,C,Gyeonggi,Normal,Male,Fashion accessories,64.26,7,22.4910,472.3110,2019-02-09,10:00,Naverpay,449.82,4.761905,22.4910,5.7,VIP,2511
293,316-68-6352,A,Seoul,Member,Female,Food and beverages,36.36,2,3.6360,76.3560,2019-01-21,10:00,Naverpay,72.72,4.761905,3.6360,7.1,NORMAL,2530
200,606-80-4905,C,Gyeonggi,Member,Female,Sports and travel,19.15,6,5.7450,120.6450,2019-01-29,10:01,Credit card,114.90,4.761905,5.7450,6.8,NORMAL,2522
669,679-22-6530,B,Incheon,Normal,Female,Sports and travel,40.62,2,4.0620,85.3020,2019-01-17,10:01,Credit card,81.24,4.761905,4.0620,4.1,NORMAL,2534
202,426-39-2418,C,Gyeonggi,Normal,Male,Electronic accessories,61.41,7,21.4935,451.3635,2019-01-14,10:02,Naverpay,429.87,4.761905,21.4935,9.8,VIP,2537
462,326-71-2155,C,Gyeonggi,Normal,Female,Sports and travel,73.95,4,14.7900,310.5900,2019-02-03,10:02,Naverpay,295.80,4.761905,14.7900,6.1,VIP,2517
468,746-19-0921,C,Gyeonggi,Normal,Male,Food and beverages,21.58,1,1.0790,22.6590,2019-02-09,10:02,Samsungpay,21.58,4.761905,1.0790,7.2,NORMAL,2511
885,460-93-5834,A,Seoul,Normal,Male,Sports and travel,45.58,7,15.9530,335.0130,2019-01-13,10:03,Naverpay,319.06,4.761905,15.9530,5.0,VIP,2538
68,232-11-3025,A,Seoul,Normal,Male,Sports and travel,78.77,10,39.3850,827.0850,2019-01-24,10:04,Naverpay,787.70,4.761905,39.3850,6.4,VVIP,2527

In [83]:
df.groupby('GENDER')['TOTAL_PRICE'].mean()

GENDER
Female    335.095659
Male      310.789226
Name: TOTAL_PRICE, dtype: float64

In [84]:
df.groupby('GENDER')['TOTAL_PRICE'].median()

GENDER
Female    272.58
Male      244.23
Name: TOTAL_PRICE, dtype: float64

In [85]:
df.groupby('GENDER', as_index=False)['TOTAL_PRICE'].median()

   GENDER  TOTAL_PRICE
0  Female       272.58
1    Male       244.23

#### crosstab

In [86]:
table1 = pd.crosstab(df['GENDER'], df['CITY'])
table1

CITY    Gyeonggi  Incheon  Seoul
GENDER
Female       178      162    161
Male         150      170    179

In [87]:
table2 = pd.crosstab(df['GENDER'], df['CITY'], normalize = 'index')
table2

CITY    Gyeonggi   Incheon     Seoul
GENDER
Female  0.355289  0.323353  0.321357
Male    0.300601  0.340681  0.358717

In [88]:
table3 = pd.crosstab(df['GENDER'], df['CITY'], normalize = 'columns')
table3

CITY    Gyeonggi   Incheon     Seoul
GENDER
Female  0.542683  0.487952  0.473529
Male    0.457317  0.512048  0.526471

In [89]:
table4 = pd.crosstab(df['GENDER'], df['CITY'], margins=True)
table4

CITY    Gyeonggi  Incheon  Seoul   All
GENDER
Female       178      162    161   501
Male         150      170    179   499
All          328      332    340  1000

In [90]:
df.head()

,ORDERID,PURCHASE_PAGE,CITY,CUSTOMER_TYPE,GENDER,PRODUCT_TYPE,UNIT_PRICE,QUANTITY,MILEAGE,TOTAL_PRICE,DATE,PURCHASE_TIME,PAYMENT,COGS,GROSS_MARGIN_PERCENTAGE,GROSS_INCOME,RATING,GRADE,TO_XMAS
0,750-67-8428,A,Seoul,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08,Samsungpay,522.83,4.761905,26.1415,9.1,VVIP,2546
1,226-31-3081,C,Gyeonggi,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29,Naverpay,76.40,4.761905,3.8200,9.6,NORMAL,2484
2,631-41-3108,A,Seoul,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23,Credit card,324.31,4.761905,16.2155,7.4,VIP,2489
3,123-19-1176,A,Seoul,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33,Samsungpay,465.76,4.761905,23.2880,8.4,VIP,2524
4,373-73-7910,A,Seoul,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37,Samsungpay,604.17,4.761905,30.2085,0.0,VVIP,2512

In [92]:
pd.crosstab(df['CUSTOMER_TYPE'], df['PURCHASE_PAGE'], margins=True)

PURCHASE_PAGE    A    B    C   All
CUSTOMER_TYPE
Member         167  165  169   501
Normal         173  167  159   499
All            340  332  328  1000

#### PIVOT TABLE

In [93]:
# 성별, 도시에 따른 price의 총합 
pivot1 = df.pivot_table(index='GENDER', columns='CITY', values='TOTAL_PRICE', aggfunc='sum')
pivot1

CITY      Gyeonggi    Incheon       Seoul
GENDER
Female  61685.4630  52928.295  53269.1670
Male    48883.2435  53269.377  52931.2035

In [96]:
# 성별, 도시에 따른 price의 평균  
pivot2 = df.pivot_table(index='GENDER', columns='CITY', values='TOTAL_PRICE', aggfunc='mean')
pivot2

CITY      Gyeonggi     Incheon       Seoul
GENDER
Female  346.547545  326.717870  330.864391
Male    325.888290  313.349276  295.705047

#### one-hot encoding 
- 단점: 클래스개수 많아지면 변수도 같이 많아짐

In [97]:
df = pd.DataFrame([
    [42, 'male', 12, 'reading', 1],
    [35, 'female', 3, 'cooking', 0],
    [27, 'female', 7, 'cycling', 2],
    [56, 'male', 21, 'swimming', 0]
])
df.columns=['age', 'gender', 'month_birth', 'hobby', 'target']
df

   age  gender  month_birth     hobby  target
0   42    male           12   reading       1
1   35  female            3   cooking       0
2   27  female            7   cycling       2
3   56    male           21  swimming       0

In [98]:
pd.get_dummies(df, dtype=float)  # 문자인것들만 dummy 변수로 바꿔줌

,age,month_birth,target,gender_female,gender_male,hobby_cooking,hobby_cycling,hobby_reading,hobby_swimming
0,42,12,1,0.0,1.0,0.0,0.0,1.0,0.0
1,35,3,0,1.0,0.0,1.0,0.0,0.0,0.0
2,27,7,2,1.0,0.0,0.0,1.0,0.0,0.0
3,56,21,0,0.0,1.0,0.0,0.0,0.0,1.0

In [100]:
pd.get_dummies(df['hobby'], dtype=float)

   cooking  cycling  reading  swimming
0      0.0      0.0      1.0       0.0
1      1.0      0.0      0.0       0.0
2      0.0      1.0      0.0       0.0
3      0.0      0.0      0.0       1.0