#### 기초수학

In [1]:
# min, argmin

x = [4, 2, 8, 9, 3]
min_value = min(x)
print(min_value)

2

In [2]:
argmin_value = x.index(min_value)
print(argmin_value)

1

In [3]:
import numpy as np
min_value = np.min(x)
print(min_value)

2

In [4]:
argmin_value = np.argmin(x)
print(argmin_value)

1

In [5]:
# max, argmax

x = [4, 2, 8, 9, 3]
max_value = max(x)
print(max_value)

9

In [7]:
argmax_value = x.index(max_value)
print(argmax_value)

3

In [11]:
max_value = np.max(x)
print(max_value)

9

In [13]:
argmax_value = np.argmax(x)
print(argmax_value)

3

#### 선형대수

In [14]:
import numpy as np
A = np.array([1,2,3,4,5,6,7,8])
print(A)

[1 2 3 4 5 6 7 8]

In [15]:
A1 = A.reshape(8, 1)
print(A1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

In [16]:
A2 = A.reshape(2, 4)
print(A2)

[[1 2 3 4]
 [5 6 7 8]]

In [17]:
np.reshape(A, (2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
A.reshape(-1, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
A.reshape(2, -1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [22]:
print(A)

[[1 2]
 [3 4]]

In [23]:
print(B)

[[5 6]
 [7 8]]

In [25]:
C = np.concatenate((A, B), axis=0)
print(C)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

In [26]:
C.shape

(4, 2)

In [28]:
D = np.concatenate((A,B), axis=1)
print(D)

[[1 2 5 6]
 [3 4 7 8]]

In [31]:
import pandas as pd 
df = pd.read_csv('./data/house_prices.csv')

In [32]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [35]:
X = df[['CRIM', 'NOX', 'RM', 'AGE', 'TAX']]
X

        CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [37]:
X_t = np.transpose(X)
X_t

,0,1,2,3,4,5,6,7,8,9,...,496,497,498,499,500,501,502,503,504,505
CRIM,0.00632,0.02731,0.02729,0.03237,0.06905,0.02985,0.08829,0.14455,0.21124,0.17004,...,0.2896,0.26838,0.23912,0.17783,0.22438,0.06263,0.04527,0.06076,0.10959,0.04741
NOX,0.53800,0.46900,0.46900,0.45800,0.45800,0.45800,0.52400,0.52400,0.52400,0.52400,...,0.5850,0.58500,0.58500,0.58500,0.58500,0.57300,0.57300,0.57300,0.57300,0.57300
RM,6.57500,6.42100,7.18500,6.99800,7.14700,6.43000,6.01200,6.17200,5.63100,6.00400,...,5.3900,5.79400,6.01900,5.56900,6.02700,6.59300,6.12000,6.97600,6.79400,6.03000
AGE,65.20000,78.90000,61.10000,45.80000,54.20000,58.70000,66.60000,96.10000,100.00000,85.90000,...,72.9000,70.60000,65.30000,73.50000,79.70000,69.10000,76.70000,91.00000,89.30000,80.80000
TAX,296.00000,242.00000,242.00000,222.00000,222.00000,222.00000,311.00000,311.00000,311.00000,311.00000,...,391.0000,391.00000,391.00000,391.00000,391.00000,273.00000,273.00000,273.00000,273.00000,273.00000

In [39]:
X_t = X.T
X_t

,0,1,2,3,4,5,6,7,8,9,...,496,497,498,499,500,501,502,503,504,505
CRIM,0.00632,0.02731,0.02729,0.03237,0.06905,0.02985,0.08829,0.14455,0.21124,0.17004,...,0.2896,0.26838,0.23912,0.17783,0.22438,0.06263,0.04527,0.06076,0.10959,0.04741
NOX,0.53800,0.46900,0.46900,0.45800,0.45800,0.45800,0.52400,0.52400,0.52400,0.52400,...,0.5850,0.58500,0.58500,0.58500,0.58500,0.57300,0.57300,0.57300,0.57300,0.57300
RM,6.57500,6.42100,7.18500,6.99800,7.14700,6.43000,6.01200,6.17200,5.63100,6.00400,...,5.3900,5.79400,6.01900,5.56900,6.02700,6.59300,6.12000,6.97600,6.79400,6.03000
AGE,65.20000,78.90000,61.10000,45.80000,54.20000,58.70000,66.60000,96.10000,100.00000,85.90000,...,72.9000,70.60000,65.30000,73.50000,79.70000,69.10000,76.70000,91.00000,89.30000,80.80000
TAX,296.00000,242.00000,242.00000,222.00000,222.00000,222.00000,311.00000,311.00000,311.00000,311.00000,...,391.0000,391.00000,391.00000,391.00000,391.00000,273.00000,273.00000,273.00000,273.00000,273.00000

In [40]:
X_t.dot(X)

              CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [41]:
X_t@X

              CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [42]:
print("행렬식(determinant) 구하기")
XtX = X_t@X
np.linalg.det(XtX)

행렬식(determinant) 구하기

7.91431657769047e+21

In [43]:
B = df[['CRIM', 'NOX']]
B['NOX3'] = B['NOX']*3

C:\Users\User\AppData\Local\Temp\ipykernel_7868\709422279.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  B['NOX3'] = B['NOX']*3

In [44]:
B

        CRIM    NOX   NOX3
0    0.00632  0.538  1.614
1    0.02731  0.469  1.407
2    0.02729  0.469  1.407
3    0.03237  0.458  1.374
4    0.06905  0.458  1.374
..       ...    ...    ...
501  0.06263  0.573  1.719
502  0.04527  0.573  1.719
503  0.06076  0.573  1.719
504  0.10959  0.573  1.719
505  0.04741  0.573  1.719

[506 rows x 3 columns]

In [46]:
BtB = B.T@B
np.round(np.linalg.det(BtB))

-0.0

In [47]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 4.07613803e-05  1.32526683e-04  4.76832932e-05 -1.01889386e-06
  -1.10744437e-06]
 [ 1.32526683e-04  3.44301609e-01 -1.30762150e-02 -8.56047279e-04
  -1.21234099e-04]
 [ 4.76832932e-05 -1.30762150e-02  9.05341934e-04  1.73338529e-05
   1.03814433e-06]
 [-1.01889386e-06 -8.56047279e-04  1.73338529e-05  5.35211609e-06
   4.19638894e-09]
 [-1.10744437e-06 -1.21234099e-04  1.03814433e-06  4.19638894e-09
   1.58047038e-07]]

In [49]:
np.round(XtX@XtX_inv)

        0    1    2    3    4
CRIM  1.0 -0.0 -0.0 -0.0  0.0
NOX  -0.0  1.0  0.0  0.0 -0.0
RM    0.0 -0.0  1.0 -0.0 -0.0
AGE   0.0 -0.0  0.0  1.0 -0.0
TAX   0.0  0.0  0.0 -0.0  1.0

In [50]:
np.round(XtX_inv@XtX)

   CRIM  NOX   RM  AGE  TAX
0   1.0 -0.0 -0.0 -0.0 -0.0
1  -0.0  1.0 -0.0 -0.0 -0.0
2   0.0  0.0  1.0  0.0  0.0
3   0.0  0.0  0.0  1.0  0.0
4   0.0  0.0  0.0  0.0  1.0

In [51]:
crim = df['CRIM']
nox = df['NOX']

In [57]:
res = np.inner(crim, nox)
print(res)

1226.123170231

In [58]:
# 대각화
cov_x = X_t.dot(X)
cov_x

              CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [59]:
e, v = np.linalg.eig(cov_x)

In [60]:
e

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [61]:
np.round(v, 2)

array([[ 0.01, -0.04, -0.99,  0.14, -0.  ],
       [ 0.  ,  0.  ,  0.01,  0.04, -1.  ],
       [ 0.01,  0.04,  0.14,  0.99,  0.04],
       [ 0.15,  0.99, -0.05, -0.04,  0.  ],
       [ 0.99, -0.15,  0.02, -0.01,  0.  ]])

In [65]:
# A = PDP_t
print("고유값, 고유벡터로 원데이터 A 복원")
A = v@np.diag(e)@v.T
pd.DataFrame(A)

고유값, 고유벡터로 원데이터 A 복원

              0              1             2             3             4
0  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
1  1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
2  1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
3  1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
4  1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

#### 기초통계