In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("./data/house_prices.csv")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
df.iloc[2,4]

np.float64(0.469)

In [4]:
df.iloc[3,5]

np.float64(6.998)

In [5]:
df.iloc[2,3] + df.iloc[4,5]

np.float64(7.147)

In [6]:
print(df.iloc[2,3] + df.iloc[4,5])

7.147

#### reshape

In [7]:
import numpy as np

In [8]:
A = np.array([1,2,3,4,5,6,7,8])
print(A)

[1 2 3 4 5 6 7 8]

In [9]:
A1 = A.reshape(8,1)
print(A1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

In [10]:
A2 = A.reshape(2,4)
print(A2)

[[1 2 3 4]
 [5 6 7 8]]

In [11]:
A3 = np.reshape(A, (2,4))
print(A3)

[[1 2 3 4]
 [5 6 7 8]]

In [12]:
A4 = A.reshape(-1,4)
print(A4)

[[1 2 3 4]
 [5 6 7 8]]

In [13]:
A5 = A.reshape(2,-1)
print(A5)

[[1 2 3 4]
 [5 6 7 8]]

In [14]:
A6 = A5.reshape(-1)
print(A6)

[1 2 3 4 5 6 7 8]

#### concatenate

In [15]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

In [16]:
C = np.concatenate((A,B), axis=0)
print(C)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

In [17]:
D = np.concatenate((A, B), axis=1)
print(D)

[[1 2 5 6]
 [3 4 7 8]]

#### 전치행렬 실습

In [18]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [19]:
X = df[['CRIM', 'NOX', 'RM', 'AGE', 'TAX']]
X

        CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [20]:
X_t = np.transpose(X)
X_t

,0,1,2,3,4,5,6,7,8,9,...,496,497,498,499,500,501,502,503,504,505
CRIM,0.00632,0.02731,0.02729,0.03237,0.06905,0.02985,0.08829,0.14455,0.21124,0.17004,...,0.2896,0.26838,0.23912,0.17783,0.22438,0.06263,0.04527,0.06076,0.10959,0.04741
NOX,0.53800,0.46900,0.46900,0.45800,0.45800,0.45800,0.52400,0.52400,0.52400,0.52400,...,0.5850,0.58500,0.58500,0.58500,0.58500,0.57300,0.57300,0.57300,0.57300,0.57300
RM,6.57500,6.42100,7.18500,6.99800,7.14700,6.43000,6.01200,6.17200,5.63100,6.00400,...,5.3900,5.79400,6.01900,5.56900,6.02700,6.59300,6.12000,6.97600,6.79400,6.03000
AGE,65.20000,78.90000,61.10000,45.80000,54.20000,58.70000,66.60000,96.10000,100.00000,85.90000,...,72.9000,70.60000,65.30000,73.50000,79.70000,69.10000,76.70000,91.00000,89.30000,80.80000
TAX,296.00000,242.00000,242.00000,222.00000,222.00000,222.00000,311.00000,311.00000,311.00000,311.00000,...,391.0000,391.00000,391.00000,391.00000,391.00000,273.00000,273.00000,273.00000,273.00000,273.00000

In [21]:
X_t = X.T
X_t

,0,1,2,3,4,5,6,7,8,9,...,496,497,498,499,500,501,502,503,504,505
CRIM,0.00632,0.02731,0.02729,0.03237,0.06905,0.02985,0.08829,0.14455,0.21124,0.17004,...,0.2896,0.26838,0.23912,0.17783,0.22438,0.06263,0.04527,0.06076,0.10959,0.04741
NOX,0.53800,0.46900,0.46900,0.45800,0.45800,0.45800,0.52400,0.52400,0.52400,0.52400,...,0.5850,0.58500,0.58500,0.58500,0.58500,0.57300,0.57300,0.57300,0.57300,0.57300
RM,6.57500,6.42100,7.18500,6.99800,7.14700,6.43000,6.01200,6.17200,5.63100,6.00400,...,5.3900,5.79400,6.01900,5.56900,6.02700,6.59300,6.12000,6.97600,6.79400,6.03000
AGE,65.20000,78.90000,61.10000,45.80000,54.20000,58.70000,66.60000,96.10000,100.00000,85.90000,...,72.9000,70.60000,65.30000,73.50000,79.70000,69.10000,76.70000,91.00000,89.30000,80.80000
TAX,296.00000,242.00000,242.00000,222.00000,222.00000,222.00000,311.00000,311.00000,311.00000,311.00000,...,391.0000,391.00000,391.00000,391.00000,391.00000,273.00000,273.00000,273.00000,273.00000,273.00000

In [22]:
X_t.dot(X)

              CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [23]:
X_t@X

              CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

#### 행렬식

In [24]:
A = df[['CRIM', 'NOX', 'NOX']]
AtA = A.T@A

In [25]:
AtA

              CRIM         NOX         NOX
CRIM  43970.343555  1226.12317  1226.12317
NOX    1226.123170   162.47038   162.47038
NOX    1226.123170   162.47038   162.47038

In [26]:
np.linalg.det(AtA)

np.float64(0.0)

In [27]:
B = df[['CRIM', 'NOX']]
B['NOX3'] = B['NOX']*3
B

C:\Users\User\AppData\Local\Temp\ipykernel_12620\406843147.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  B['NOX3'] = B['NOX']*3

        CRIM    NOX   NOX3
0    0.00632  0.538  1.614
1    0.02731  0.469  1.407
2    0.02729  0.469  1.407
3    0.03237  0.458  1.374
4    0.06905  0.458  1.374
..       ...    ...    ...
501  0.06263  0.573  1.719
502  0.04527  0.573  1.719
503  0.06076  0.573  1.719
504  0.10959  0.573  1.719
505  0.04741  0.573  1.719

[506 rows x 3 columns]

In [28]:
BtB = B.T@B 
BtB

              CRIM         NOX         NOX3
CRIM  43970.343555  1226.12317  3678.369511
NOX    1226.123170   162.47038   487.411140
NOX3   3678.369511   487.41114  1462.233421

In [29]:
np.linalg.det(BtB)

np.float64(-2.885627942171323e-06)

#### 역행렬 실습

In [30]:
XtX = X_t@X
XtX

              CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [31]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 4.07613803e-05,  1.32526683e-04,  4.76832932e-05,
        -1.01889386e-06, -1.10744437e-06],
       [ 1.32526683e-04,  3.44301609e-01, -1.30762150e-02,
        -8.56047279e-04, -1.21234099e-04],
       [ 4.76832932e-05, -1.30762150e-02,  9.05341934e-04,
         1.73338529e-05,  1.03814433e-06],
       [-1.01889386e-06, -8.56047279e-04,  1.73338529e-05,
         5.35211609e-06,  4.19638894e-09],
       [-1.10744437e-06, -1.21234099e-04,  1.03814433e-06,
         4.19638894e-09,  1.58047038e-07]])

- 에러나는 경우

In [32]:
X = df[['CRIM', 'NOX', 'NOX']]
X

        CRIM    NOX    NOX
0    0.00632  0.538  0.538
1    0.02731  0.469  0.469
2    0.02729  0.469  0.469
3    0.03237  0.458  0.458
4    0.06905  0.458  0.458
..       ...    ...    ...
501  0.06263  0.573  0.573
502  0.04527  0.573  0.573
503  0.06076  0.573  0.573
504  0.10959  0.573  0.573
505  0.04741  0.573  0.573

[506 rows x 3 columns]

In [33]:
X_t = X.T

In [34]:
XtX = X_t@X
XtX

              CRIM         NOX         NOX
CRIM  43970.343555  1226.12317  1226.12317
NOX    1226.123170   162.47038   162.47038
NOX    1226.123170   162.47038   162.47038

In [35]:
np.linalg.inv(XtX)

LinAlgError: Singular matrix

#### 내적

In [ ]:
crim = df['CRIM']
nox = df['NOX']

In [ ]:
res = np.inner(crim, nox)
print(res)

#### 대각화

In [36]:
X = df[['CRIM', 'NOX', 'RM', 'AGE', 'TAX']]
X

        CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [37]:
X_t = X.T

In [38]:
cov_x = X_t.dot(X)  
cov_x

              CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [39]:
e, v = np.linalg.eig(cov_x)
e

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [40]:
v

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])

In [41]:
np.round(v,2)

array([[ 0.01, -0.04, -0.99,  0.14, -0.  ],
       [ 0.  ,  0.  ,  0.01,  0.04, -1.  ],
       [ 0.01,  0.04,  0.14,  0.99,  0.04],
       [ 0.15,  0.99, -0.05, -0.04,  0.  ],
       [ 0.99, -0.15,  0.02, -0.01,  0.  ]])

#### 특이값분해 실습

In [42]:
e, v = np.linalg.eig(cov_x)
e

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [43]:
v

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])

In [44]:
u, s, vt = np.linalg.svd(cov_x)

In [45]:
u

array([[-1.17248568e-02,  4.34541539e-02,  9.89273583e-01,
        -1.38967257e-01, -3.78876853e-04],
       [-1.21545113e-03, -3.97729110e-03, -5.48368537e-03,
        -3.74537281e-02, -9.99274663e-01],
       [-1.28461807e-02, -4.11504926e-02, -1.37240647e-01,
        -9.88869506e-01,  3.79962757e-02],
       [-1.54544362e-01, -9.86199762e-01,  4.66395497e-02,
         3.66695593e-02,  2.48287726e-03],
       [-9.87832003e-01,  1.54313263e-01, -1.72471505e-02,
         8.81831838e-03,  3.51466736e-04]])

In [46]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [47]:
vt

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [ 4.34541539e-02, -3.97729110e-03, -4.11504926e-02,
        -9.86199762e-01,  1.54313263e-01],
       [ 9.89273583e-01, -5.48368537e-03, -1.37240647e-01,
         4.66395497e-02, -1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])

In [48]:
u2, s2, vt2 = np.linalg.svd(X)

In [49]:
u2

array([[-0.03008946,  0.03086023,  0.01712144, ..., -0.00411115,
        -0.00427013, -0.00365704],
       [-0.02499491,  0.06652264,  0.00780423, ..., -0.05447262,
        -0.05387641, -0.05180949],
       [-0.02472231,  0.03790476,  0.0132068 , ..., -0.01726598,
        -0.01167245,  0.01252377],
       ...,
       [-0.02822706,  0.07823426,  0.00788495, ...,  0.99280739,
        -0.00687219, -0.00535758],
       [-0.02820076,  0.07548049,  0.00791964, ..., -0.00689953,
         0.99336613, -0.00536756],
       [-0.02806907,  0.0617432 ,  0.00995976, ..., -0.00551636,
        -0.00549819,  0.99463978]], shape=(506, 506))

In [50]:
s2

array([1.00553387e+04, 6.12306718e+02, 1.73076199e+02, 4.90216487e+01,
       1.70300420e+00])

In [52]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [51]:
vt2

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [-4.34541539e-02,  3.97729110e-03,  4.11504926e-02,
         9.86199762e-01, -1.54313263e-01],
       [-9.89273583e-01,  5.48368537e-03,  1.37240647e-01,
        -4.66395497e-02,  1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])

In [53]:
s2**2

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])