[데이터 링크](https://www.kaggle.com/datasets/laotse/credit-risk-dataset/data)

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df_bak = pd.read_csv("./credit_risk_dataset.csv")
df_bak

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [4]:
df = df_bak.iloc[:,:]
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [5]:
df.shape

(32581, 12)

In [6]:
df.columns

Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [15]:
df[now_col].dtypes == 'int64'

True

In [17]:
for now_col in df.columns:
    if df[now_col].dtypes == 'int64' or df[now_col].dtypes == 'float64': 
        print(now_col, "\n",df[now_col].min(), " ", df[now_col].max())
    else:
        print(now_col, "\n",df[now_col].unique())

person_age
 20   144
person_income
 4000   6000000
person_home_ownership
 ['RENT' 'OWN' 'MORTGAGE' 'OTHER']
person_emp_length
 0.0   123.0
loan_intent
 ['PERSONAL' 'EDUCATION' 'MEDICAL' 'VENTURE' 'HOMEIMPROVEMENT'
 'DEBTCONSOLIDATION']
loan_grade
 ['D' 'B' 'C' 'A' 'E' 'F' 'G']
loan_amnt
 500   35000
loan_int_rate
 5.42   23.22
loan_status
 0   1
loan_percent_income
 0.0   0.83
cb_person_default_on_file
 ['Y' 'N']
cb_person_cred_hist_length
 2   30

In [18]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [19]:
df.shape

(32581, 12)

In [21]:
df = df.fillna(0)
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [22]:
df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [23]:
df.select_dtypes(include=['object'])

,person_home_ownership,loan_intent,loan_grade,cb_person_default_on_file
0,RENT,PERSONAL,D,Y
1,OWN,EDUCATION,B,N
2,MORTGAGE,MEDICAL,C,N
3,RENT,MEDICAL,C,N
4,RENT,MEDICAL,C,Y
...,...,...,...,...
32576,MORTGAGE,PERSONAL,C,N
32577,MORTGAGE,PERSONAL,A,N
32578,RENT,HOMEIMPROVEMENT,B,N
32579,MORTGAGE,PERSONAL,B,N
32580,RENT,MEDICAL,B,N

### loan_grade 예측변수 encoding 
- 트리 기반 변수에는 1,2,3,4..로 인코딩

In [25]:
le = LabelEncoder()

In [26]:
df['loan_grade_encoded'] = le.fit_transform(df['loan_grade'])
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_grade_encoded
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,1
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,2
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30,2
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19,0
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28,1
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26,1
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30,1

In [27]:
df = df.drop(columns=['loan_grade'])
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_grade_encoded
0,22,59000,RENT,123.0,PERSONAL,35000,16.02,1,0.59,Y,3,3
1,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,1
2,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,2
3,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2
4,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,5800,13.16,0,0.11,N,30,2
32577,54,120000,MORTGAGE,4.0,PERSONAL,17625,7.49,0,0.15,N,19,0
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,35000,10.99,1,0.46,N,28,1
32579,56,150000,MORTGAGE,5.0,PERSONAL,15000,11.48,0,0.10,N,26,1
32580,66,42000,RENT,2.0,MEDICAL,6475,9.99,0,0.15,N,30,1

### x 변수들은 one hot encoding

In [35]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_grade_encoded
0,22,59000,RENT,123.0,PERSONAL,35000,16.02,1,0.59,Y,3,3
1,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,1
2,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,2
3,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2
4,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,2

In [29]:
df.select_dtypes(include=['object'])

      person_home_ownership      loan_intent cb_person_default_on_file
0                      RENT         PERSONAL                         Y
1                       OWN        EDUCATION                         N
2                  MORTGAGE          MEDICAL                         N
3                      RENT          MEDICAL                         N
4                      RENT          MEDICAL                         Y
...                     ...              ...                       ...
32576              MORTGAGE         PERSONAL                         N
32577              MORTGAGE         PERSONAL                         N
32578                  RENT  HOMEIMPROVEMENT                         N
32579              MORTGAGE         PERSONAL                         N
32580                  RENT          MEDICAL                         N

[32581 rows x 3 columns]

In [34]:
pd.get_dummies(df, dtype=float).columns

Index(['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_cred_hist_length', 'loan_grade_encoded',
       'person_home_ownership_MORTGAGE', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_DEBTCONSOLIDATION', 'loan_intent_EDUCATION',
       'loan_intent_HOMEIMPROVEMENT', 'loan_intent_MEDICAL',
       'loan_intent_PERSONAL', 'loan_intent_VENTURE',
       'cb_person_default_on_file_N', 'cb_person_default_on_file_Y'],
      dtype='object')