In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, balanced_accuracy_score
from sklearn.preprocessing import LabelEncoder

In [2]:
df_bak = pd.read_csv("./credit_risk_dataset.csv")
df_bak

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [3]:
df = df_bak.iloc[:,:]

In [4]:
df[['loan_grade']].value_counts()

loan_grade
A             10777
B             10451
C              6458
D              3626
E               964
F               241
G                64
Name: count, dtype: int64

In [5]:
le = LabelEncoder()

In [6]:
df['loan_grade_encoded'] = le.fit_transform(df['loan_grade']) 
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_grade_encoded
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,1
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,2
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30,2
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19,0
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28,1
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26,1
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30,1

In [7]:
df = df.drop(columns=['loan_grade']) 
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_grade_encoded
0,22,59000,RENT,123.0,PERSONAL,35000,16.02,1,0.59,Y,3,3
1,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,1
2,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,2
3,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2
4,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,5800,13.16,0,0.11,N,30,2
32577,54,120000,MORTGAGE,4.0,PERSONAL,17625,7.49,0,0.15,N,19,0
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,35000,10.99,1,0.46,N,28,1
32579,56,150000,MORTGAGE,5.0,PERSONAL,15000,11.48,0,0.10,N,26,1
32580,66,42000,RENT,2.0,MEDICAL,6475,9.99,0,0.15,N,30,1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_amnt                   32581 non-null  int64
 6   loan_int_rate               29465 non-null  float64
 7   loan_status                 32581 non-null  int64
 8   loan_percent_income         32581 non-null  float64
 9   cb_person_default_on_file   32581 non-null  object
 10  cb_person_cred_hist_length  32581 non-null  int64
 11  loan_grade_encoded          32581 non-null  int64
dtypes: float64(3), int64(6), object(3)
memory usage: 3.0+ MB

In [9]:
# df = df.select_dtypes(exclude=['object'])

In [10]:
df = pd.get_dummies(df, dtype=float)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      32581 non-null  int64
 1   person_income                   32581 non-null  int64
 2   person_emp_length               31686 non-null  float64
 3   loan_amnt                       32581 non-null  int64
 4   loan_int_rate                   29465 non-null  float64
 5   loan_status                     32581 non-null  int64
 6   loan_percent_income             32581 non-null  float64
 7   cb_person_cred_hist_length      32581 non-null  int64
 8   loan_grade_encoded              32581 non-null  int64
 9   person_home_ownership_MORTGAGE  32581 non-null  float64
 10  person_home_ownership_OTHER     32581 non-null  float64
 11  person_home_ownership_OWN       32581 non-null  float64
 12  person_home_ownership_RENT      32581 non-null  float64
 13  loan_intent_DEBTCONSOLIDATION   32581 non-null  float64
 14  loan_intent_EDUCATION           32581 non-null  float64
 15  loan_intent_HOMEIMPROVEMENT     32581 non-null  float64
 16  loan_intent_MEDICAL             32581 non-null  float64
 17  loan_intent_PERSONAL            32581 non-null  float64
 18  loan_intent_VENTURE             32581 non-null  float64
 19  cb_person_default_on_file_N     32581 non-null  float64
 20  cb_person_default_on_file_Y     32581 non-null  float64
dtypes: float64(15), int64(6)
memory usage: 5.2 MB

In [12]:
target_col = 'loan_grade_encoded'

X = df.drop(columns=[target_col])
y = df[target_col]

# ------------------------------------------------------------
# (A) Stratified split: 클래스 "비율"을 유지하여 train/test 분할
#     (데이터 본연의 비율을 보존하면서 공정하게 평가하고 싶을 때)
# ------------------------------------------------------------
X_train_A, X_test_A, y_train_A, y_test_A = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

rf_A = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    n_jobs=-1,
    random_state=42
)
rf_A.fit(X_train_A, y_train_A)

pred_A = rf_A.predict(X_test_A)

print("=== (A) Stratified split 결과 ===")
print("Balanced Accuracy:", balanced_accuracy_score(y_test_A, pred_A).round(4))
print(classification_report(y_test_A, pred_A, digits=4))
print("Confusion Matrix:\n", confusion_matrix(y_test_A, pred_A))

=== (A) Stratified split 결과 ===
Balanced Accuracy: 0.583
              precision    recall  f1-score   support

           0     0.9473    0.9258    0.9364      2156
           1     0.8636    0.9569    0.9079      2090
           2     0.8968    0.8204    0.8569      1292
           3     0.7084    0.7876    0.7459       725
           4     0.5714    0.2694    0.3662       193
           5     0.6154    0.1667    0.2623        48
           6     1.0000    0.1538    0.2667        13

    accuracy                         0.8729      6517
   macro avg     0.8004    0.5830    0.6203      6517
weighted avg     0.8704    0.8729    0.8671      6517

Confusion Matrix:
 [[1996  156    2    2    0    0    0]
 [  87 2000    1    2    0    0    0]
 [  22  125 1060   85    0    0    0]
 [   2   28  105  571   19    0    0]
 [   0    5   10  124   52    2    0]
 [   0    2    3   21   14    8    0]
 [   0    0    1    1    6    3    2]]