## 파이캐럿_분류

In [1]:
import pandas as pd
from pycaret.classification import *
df = pd.read_csv('credit_risk_dataset.csv')

In [2]:
df = df.drop('loan_int_rate', axis=1)
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,1,0.55,Y,4

In [3]:
exp1 = setup(data=df, target='loan_grade', session_id=123)

In [4]:
best_model = compare_models()

In [5]:
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [6]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [7]:
final_model = finalize_model(tuned_model)

In [8]:
save_model(final_model, 'credit_risk_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['person_age', 'person_income',
                                              'person_emp_length', 'loan_amnt',
                                              'loan_status',
                                              'loan_percent_income',
                                              'cb_person_cred_hist_length'],
                                     transformer=S...
                  LGBMClassifier(boosting_type='gbdt', class_weight=None,
                                 colsample_bytree=1.0, importance_type='split',
                                 learning_rate=0.1, max_depth=-1,
                                 min_child_samples=20, min_child_weight=0.001,
                                 min_split_gain=0.0, n_estimators=100, n_jobs=-1,
                                 num_leaves=31, objective=None, random_state=123,
                                 reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
                                 subsample_for_bin=200000, subsample_freq=0))],
          verbose=False),
 'credit_risk_model.pkl')

In [9]:
loaded_model = load_model('credit_risk_model')

Transformation Pipeline and Model Successfully Loaded

In [20]:
new_data = df.iloc[20:40, 0:]
new_data

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
20,25,162500,RENT,2.0,VENTURE,A,35000,0,0.22,N,4
21,25,137000,RENT,9.0,PERSONAL,E,34800,0,0.25,Y,2
22,22,65000,RENT,4.0,EDUCATION,D,34000,1,0.52,N,4
23,24,10980,OWN,0.0,PERSONAL,A,1500,0,0.14,N,3
24,22,80000,RENT,3.0,PERSONAL,D,33950,1,0.42,Y,4
25,24,67746,RENT,8.0,HOMEIMPROVEMENT,C,33000,1,0.49,N,3
26,21,11000,MORTGAGE,3.0,VENTURE,E,4575,1,0.42,Y,3
27,23,11000,OWN,0.0,PERSONAL,A,1400,0,0.13,N,3
28,24,65000,RENT,6.0,HOMEIMPROVEMENT,B,32500,1,0.50,N,3
29,21,11389,OTHER,5.0,EDUCATION,C,4000,1,0.35,Y,2
30,21,11520,OWN,5.0,MEDICAL,B,2000,1,0.17,N,3
31,25,120000,RENT,2.0,VENTURE,A,32000,0,0.27,N,2
32,26,95000,RENT,7.0,HOMEIMPROVEMENT,C,31050,1,0.33,Y,3
33,25,306000,RENT,2.0,DEBTCONSOLIDATION,C,24250,0,0.08,N,3
34,26,300000,MORTGAGE,10.0,MEDICAL,C,7800,0,0.03,N,4
35,21,12000,OWN,5.0,EDUCATION,A,2500,1,0.21,N,4
36,22,48000,RENT,1.0,EDUCATION,E,30000,1,0.63,N,2
37,24,64000,RENT,8.0,DEBTCONSOLIDATION,D,30000,1,0.47,Y,3
38,25,75000,RENT,4.0,HOMEIMPROVEMENT,D,30000,1,0.40,Y,4
39,23,71500,RENT,3.0,DEBTCONSOLIDATION,D,30000,1,0.42,N,4

In [21]:
predictions = predict_model(loaded_model, data=new_data)

In [22]:
predictions

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_grade,prediction_label,prediction_score
20,25,162500,RENT,2.0,VENTURE,35000,0,0.22,N,4,A,A,0.6353
21,25,137000,RENT,9.0,PERSONAL,34800,0,0.25,Y,2,E,E,0.4356
22,22,65000,RENT,4.0,EDUCATION,34000,1,0.52,N,4,D,B,0.3405
23,24,10980,OWN,0.0,PERSONAL,1500,0,0.14,N,3,A,B,0.3595
24,22,80000,RENT,3.0,PERSONAL,33950,1,0.42,Y,4,D,D,0.7256
25,24,67746,RENT,8.0,HOMEIMPROVEMENT,33000,1,0.49,N,3,C,B,0.3449
26,21,11000,MORTGAGE,3.0,VENTURE,4575,1,0.42,Y,3,E,C,0.5809
27,23,11000,OWN,0.0,PERSONAL,1400,0,0.13,N,3,A,A,0.3699
28,24,65000,RENT,6.0,HOMEIMPROVEMENT,32500,1,0.50,N,3,B,B,0.3487
29,21,11389,OTHER,5.0,EDUCATION,4000,1,0.35,Y,2,C,C,0.7256
30,21,11520,OWN,5.0,MEDICAL,2000,1,0.17,N,3,B,B,0.4269
31,25,120000,RENT,2.0,VENTURE,32000,0,0.27,N,2,A,A,0.7410
32,26,95000,RENT,7.0,HOMEIMPROVEMENT,31050,1,0.33,Y,3,C,C,0.4424
33,25,306000,RENT,2.0,DEBTCONSOLIDATION,24250,0,0.08,N,3,C,C,0.6121
34,26,300000,MORTGAGE,10.0,MEDICAL,7800,0,0.03,N,4,C,B,0.4423
35,21,12000,OWN,5.0,EDUCATION,2500,1,0.21,N,4,A,B,0.5531
36,22,48000,RENT,1.0,EDUCATION,30000,1,0.63,N,2,E,B,0.3098
37,24,64000,RENT,8.0,DEBTCONSOLIDATION,30000,1,0.47,Y,3,D,D,0.6673
38,25,75000,RENT,4.0,HOMEIMPROVEMENT,30000,1,0.40,Y,4,D,D,0.6800
39,23,71500,RENT,3.0,DEBTCONSOLIDATION,30000,1,0.42,N,4,D,D,0.3675