## 지도학습(1)_KNN

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [3]:
df['class'].unique()

array([0, 1, 2])

In [4]:
features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
X = df[features]
y = df['class']

In [5]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int64

In [7]:
y.value_counts()

class
0    50
1    50
2    50
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=0, stratify=y) # todo) 숙제 stratify 적용해보기 
# X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=0)

In [9]:
y_tn.value_counts()  # stratify 옵션을 적용하면 비율이 아래와 같이 유지됨.

class
2    38
1    37
0    37
Name: count, dtype: int64

In [10]:
y_te.value_counts()  # stratify 옵션을 적용하면 비율이 아래와 같이 유지됨.

class
0    13
1    13
2    12
Name: count, dtype: int64

In [12]:
# Standardization 
from sklearn.preprocessing import StandardScaler 
std_scale = StandardScaler()  # 표준화 장치 생성 (객체)
std_scale.fit(X_tn)  # 표준화에 필요한 평균, 표준편차 계산 (X train 데이터를 기준으로)
X_tn_std = std_scale.transform(X_tn)  # 위의 평균, 표준편차로 X train 데이터 변환 
X_te_std = std_scale.transform(X_te)  # 위의 평균, 표준편차로 X test 데이터 변환

In [44]:
# 학습 
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=2)  # k=2일때가 주변 k값들보다 성능 안좋은듯?
clf_knn.fit(X_tn_std, y_tn)

KNeighborsClassifier(n_neighbors=2)

In [45]:
# 예측 
knn_pred = clf_knn.predict(X_te_std)
print(knn_pred)

[0 0 0 0 1 1 1 0 1 2 2 2 1 2 1 0 0 2 0 1 2 1 1 0 1 0 0 1 1 1 0 1 2 2 0 1 2
 2]

In [46]:
# 정확도 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, knn_pred)
print(accuracy)

0.9473684210526315

In [47]:
# 정밀도 (precision)
from sklearn.metrics import precision_score
precision = precision_score(y_te, knn_pred, average='macro')
print(precision)

0.9555555555555556

In [48]:
# 리콜 (Recall)
from sklearn.metrics import recall_score
recall = recall_score(y_te, knn_pred, average='macro')
print(recall)

0.9444444444444445

In [49]:
# F1 Score
from sklearn.metrics import f1_score
f1 = f1_score(y_te, knn_pred, average='macro')
print(f1)

0.9458874458874459

In [50]:
# confusion matrix 확인
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, knn_pred)  # 실제, 예측 순서로 데이터 들어감 
print(conf_matrix)

[[13  0  0]
 [ 0 13  0]
 [ 0  2 10]]

In [52]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_report = classification_report(y_te, knn_pred)  # 실제, 예측 순서로 데이터 들어감 
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.87      1.00      0.93        13
           2       1.00      0.83      0.91        12

    accuracy                           0.95        38
   macro avg       0.96      0.94      0.95        38
weighted avg       0.95      0.95      0.95        38